{{ if .Values.enableMetrics }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "sparkoperator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sparkoperator.name" . }}
    helm.sh/chart: {{ include "sparkoperator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.metricsPort }}
    targetPort: {{ .Values.metricsPort }}
    name: metrics
  selector:
    app.kubernetes.io/name: {{ include "sparkoperator.name" . }}
    app.kubernetes.io/version: {{ .Values.operatorVersion }}
{{ end }}