apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpc-leader-election-rolebinding
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpc-leader-election-role
subjects:
- kind: ServiceAccount
  name: hpc-manager
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
