dependencies:
- name: spark
  condition: k8s-big-data.spark.enabled,spark.enabled
  repository: file://./charts/spark
- name: elasticsearch
  condition: k8s-big-data.elasticsearch.enabled,elasticsearch.enabled
  repository: file://./charts/elasticsearch
- name: kibana
  condition: k8s-big-data.kibana.enabled,kibana.enabled
  repository: file://./charts/kibana
- name: hbase
  condition: k8s-big-data.hbase.enabled,hbase.enabled
  repository: file://./charts/hbase
- name: hive
  condition: k8s-big-data.hive.enabled,hive.enabled
  repository: file://./charts/hive
- name: impala
  condition: k8s-big-data.impala.enabled,impala.enabled
  repository: file://./charts/impala
- name: kudu
  condition: k8s-big-data.kudu.enabled,kudu.enabled
  repository: file://./charts/kudu
- name: client
  condition: k8s-big-data.client.enabled,client.enabled
  repository: file://./charts/client
- name: hadoop
  condition: k8s-big-data.hadoop.enabled,hadoop.enabled
  repository: file://./charts/hadoop
- name: zookeeper
  condition: k8s-big-data.zookeeper.enabled,zookeeper.enabled
  repository: file://./charts/zookeeper
- name: prometheus-operator
  condition: k8s-big-data.prometheus-operator.enabled,prometheus-operator.enabled
  repository: file://./charts/prometheus-operator
- name: sparkoperator
  condition: k8s-big-data.sparkoperator.enabled,sparkoperator.enabled
  repository: file://./charts/sparkoperator
- name: kube-state-metrics
  condition: k8s-big-data.kube-state-metrics.enabled,kube-state-metrics.enabled
  repository: file://./charts/kube-state-metrics
- name: prometheus-node-exporter
  condition: k8s-big-data.prometheus-node-exporter.enabled,prometheus-node-exporter.enabled
  repository: file://./charts/prometheus-node-exporter
- name: grafana
  condition: k8s-big-data.grafana.enabled,grafana.enabled
  repository: file://./charts/grafana
- name: custom-config
  condition: k8s-big-data.custom-config.enabled,custom-config.enabled
  repository: file://./charts/custom-config
- name: volcano
  condition: k8s-big-data.volcano.enabled,volcano.enabled
  repository: file://./charts/volcano
- name: flink-operator
  condition: k8s-big-data.flink-operator.enabled,flink-operator.enabled
  repository: file://./charts/flink-operator
- name: cp-helm-charts
  condition: k8s-big-data.cp-helm-charts.enabled,cp-helm-charts.enabled
  repository: file://./charts/cp-helm-charts
- name: airflow
  condition: k8s-big-data.airflow.enabled,airflow.enabled
  repository: file://./charts/airflow
- name: nginx-ingress
  condition: k8s-big-data.nginx-ingress.enabled,nginx-ingress.enabled
  repository: file://./charts/nginx-ingress
- name: mist
  condition: k8s-big-data.mist.enabled,mist.enabled
  repository: file://./charts/mist
- name: superset
  condition: k8s-big-data.superset.enabled,superset.enabled
  repository: file://./charts/superset
- name: postgresql
  condition: k8s-big-data.postgresql.enabled,postgresql.enabled
  repository: file://./charts/postgresql
- name: postgresql-ha
  condition: k8s-big-data.postgresql-ha.enabled,postgresql-ha.enabled
  repository: file://./charts/postgresql-ha
- name: loki
  condition: k8s-big-data.loki.enabled,loki.enabled
  repository: file://./charts/loki
- name: promtail
  condition: k8s-big-data.promtail.enabled,promtail.enabled
  repository: file://./charts/promtail