{{- if .Values.lowPriorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  labels:
    {{- include "tke-autoscaling-placeholder.labels" . | nindent 4 }}
  name: {{ .Values.lowPriorityClass.name }}
value: -1
description: "low priority class"
{{- end }}