apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}
  labels:
    app: {{ template "cp-schema-registry.name" . }}
    chart: {{ template "cp-schema-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: schema-registry
      port: {{ .Values.servicePort }}

      {{- if .Values.nodeport.enabled }}
      nodePort: {{ .Values.nodeport.port }}
      {{- end }}
    {{- if .Values.prometheus.jmx.enabled }}
    - name: jmx
      port: {{ .Values.jmx.port }}
    - name: prometheus-jmx
      port: {{ .Values.prometheus.jmx.port }}
    {{- end }}

  selector:
    app: {{ template "cp-schema-registry.name" . }}
    release: {{ .Release.Name }}

  {{- if .Values.nodeport.enabled }}
  type: NodePort
  {{- end }}