{{- if .Values.certmanager.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-certmanager-webhook
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "{{ .Chart.AppVersion }}"
spec:
  selector:
    matchLabels:
      app: net-certmanager-webhook
      role: net-certmanager-webhook
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: net-certmanager-webhook
        role: net-certmanager-webhook
        serving.knative.dev/release: "{{ .Chart.AppVersion }}"
    spec:
      serviceAccountName: controller
      containers:
      - name: webhook
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: "{{ .Values.certmanager.webhookimage }}"
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - # TODO(https://github.com/knative/pkg/pull/953): Remove stackdriver specific config
          name: METRICS_DOMAIN
          value: knative.dev/net-certmanager
        - name: WEBHOOK_NAME
          value: net-certmanager-webhook
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8008
        - name: https-webhook
          containerPort: 8443
    {{- if .Values.istio.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.istio.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.istio.tolerations }}
      tolerations:
{{ toYaml .Values.istio.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.istio.affinity }}
      affinity:
{{ toYaml .Values.istio.affinity | indent 8 }}
    {{- end }}

---
{{- end }}
