{{- if .Values.master.storage.enableLocalPv }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kudu-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}