apiVersion: v1
kind: Service
metadata:
  name: {{ template "server.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.server.component }}"
spec:
  ports:
    - port: 10000
      name: thrift
      {{ if (eq "NodePort" .Values.server.serviceType) }}
      nodePort:  {{ .Values.server.thrift.nodePort }}
      {{ end }}
    - port: 10002
      name: web
      {{ if (eq "NodePort" .Values.server.serviceType) }}
      nodePort: {{ .Values.server.web.nodePort }}
      {{ end }}
    {{- if .Values.global.metrics.enabled }}
    - port: {{ .Values.global.metrics.port }}
      name: metrics
    {{- end }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.server.component }}"
  type: {{ .Values.server.serviceType }}