{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mist.serviceAccountName" . }}
  labels:
{{ include "mist.labels" . | indent 4 }}
{{- end -}}
