apiVersion: v1
kind: Service
metadata:
  name: {{ include "mist.fullname" . }}
  labels:
{{ include "mist.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mist.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
