apiVersion: v3
name: jmeter-suite
description: A Helm chart for jmeter suit.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

keywords:
  - distributed-jmeter
  - grafana
  - influxdb

maintainers:
  - name: duckzheng
    email: duckzheng@tencent.com

dependencies:
  - name: distributed-jmeter
    condition: distributed-jmeter.enabled
    repository: file://../charts/jmeter
  - name: grafana
    condition: grafana.enabled
    repository: file://../charts/grafana
  - name: influxdb
    condition: influxdb.enabled
    repository: file://../charts/influxdb

icon: https://github.com/tkestack/charts/raw/main/icons/jmeter-suite.png
home: https://github.com/tkestack/charts
