# Default values for jmeter-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

distributed-jmeter:
  enabled: true
  server:
    replicaCount: 3
    heap_size: 2g
  master:
    heap_size: 2g

grafana:
  enabled: true

influxdb:
  enabled: true
  persistence:
    enabled: true
    ## influxdb data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    size: 20Gi
