apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monkey.fullname" . }}
  labels:
    {{- include "monkey.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: monkey-web
      qcloud-app: monkey-web
  template:
    metadata:
      labels:
        k8s-app: monkey-web
        qcloud-app: monkey-web
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: JAVA_HOME
          value: /usr
        - name: secret_id
          value: "{{.Values.secretId}}"
        - name: secret_key
          value: "{{.Values.secretKey}}"
        - name: MONKEY_SETTINGS
          value: staging
        - name: ALLOWED_IP
          value: {{.Values.allowedIp}}
        # - name: ALLOWED_DOMAIN
        #   value: .Values.allowed_domain
        - name: IS_TENCENT
          value: "false"
        - name: BUG_BUCKET
          value: "{{ .Values.bugBucket }}"
        - name: APK_BUCKET
          value: "{{ .Values.apkBucket }}"
        - name: BUCKET_REGION
          value: "{{ .Values.bucketRegion }}"
        - name: DATABASES_NAME
          value: "{{ .Values.databaseName }}"
        - name: DATABASES_USER
          value: "{{ .Values.databaseUser }}"
        - name: DATABASES_PASSWORD
          value: "{{ .Values.databasePassword }}"
        - name: DATABASES_HOST
          value: "{{ .Values.databaseHost }}"
        - name: DATABASES_PORT
          value: "{{ .Values.databasePort }}"
        - name: api_key
          value: "{{ .Values.tapdKey }}"
        - name: api_secret
          value: "{{ .Values.tapdSecret }}"
        - name: SDK_VERSION
          value: "{{ .Values.sdkVersion }}"
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: monkey-web
        resources:
          limits:
            cpu: 1024m
            memory: 2048Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: /data/service/source
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

