apiVersion: v1
kind: Service
metadata:
  name: monkey-web
spec:
  ports:
  - name: tcp-8095-80
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8095
  selector:
    k8s-app: monkey-web
    qcloud-app: monkey-web
  sessionAffinity: None
  type: NodePort
