{{- if  .Values.global.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hdfs-k8s.journalnode.fullname" . }}-dashboards
  labels:
    {{- if .Values.global.grafana.dashboardsLabel }}
    {{ .Values.global.grafana.dashboardsLabel }}: "1"
    {{- end }}
    app: {{ template "hdfs-k8s.journalnode.name" . }}
    chart: {{ template "hdfs-k8s.subchart" . }}
    release: {{ .Release.Name }}
data:
  journalnode.json: |-
{{ .Files.Get "dashboards/journalnode.json" | indent 4 }}
{{- end -}}